apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
      owner: devops
  template:
    metadata:
      labels:
        app: nginx
        owner: devops
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest

